name: Update KrishnaTV Playlist

on:
  schedule:
    - cron: "30 2 * * *"
    - cron: "30 14 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest playlist
        run: |
          curl -L "https://jootv13m.playlivtvlinks.workers.dev/" -o krishna.m3u
          curl -L "https://stream.kliv.fun/system/exc2/playlist.php?token=KPXbaIFv" -o krishna5.m3u

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add krishna.m3u krishna5.m3u
          git commit -m "Auto update playlist (12h)" || echo "No changes"
          git push
